name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Deploy to Server
      run: |
        ssh root@h2955797.stratoserver.net "cd /root/github/test-py-cicd; git pull origin main; python main.py"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
